branch-defaults:
  default:
    environment: ht-api-stg-dev
environment-defaults:
  ht-api-stg-dev:
    branch: null
    repository: null
global:
  application_name: ht-api-stg
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Docker running on
    64bit Amazon Linux/2.12.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
