branch-defaults:
  default:
    environment: ht-api-stg-dev
    group_suffix: null
global:
  application_name: ht-api-stg
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker 18.06.1-ce
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
