version: "3"

services:
  api:
    image: rehashstudio2017/ht-api
    ports:
      - 80:3000
    env_file: .env
    networks:
      - frontend
    deploy:
      replicas: 6
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

networks:
  frontend:
