export {default as hasOauthBearer} from './hasOauthBearer'
export {default as hasClientId} from './hasClientId'
export {default as hasValidOauth} from './hasValidOauth'
// export {default as multer} from './multer-s3'
export {default as multer} from './multer-cloudinary'
