const settings = {
  API_URL: process.env.REACT_APP_API_URL,
  SITE_URL: process.env.REACT_APP_SITE_URL,
  FB_APP_ID: process.env.REACT_APP_FB_APP_ID,
  cdnBaseUrl: process.env.REACT_APP_CDN_BASE_URL,
  cloudName: process.env.REACT_APP_CLOUD_NAME,
  imagePreset: process.env.REACT_APP_IMAGE_PRESET,
  videoPreset: process.env.REACT_APP_VIDEO_PRESET,

  SEARCH_APP_NAME: process.env.REACT_APP_SEARCH_APP_NAME,
  SEARCH_API_KEY: process.env.REACT_APP_SEARCH_API_KEY,
  SEARCH_STORY_INDEX: process.env.REACT_APP_SEARCH_STORY_INDEX,
  SEARCH_GUIDE_INDEX: process.env.REACT_APP_SEARCH_GUIDE_INDEX,
  SEARCH_USER_INDEX: process.env.REACT_APP_SEARCH_USER_INDEX,
  SEARCH_CATEGORIES_INDEX: process.env.REACT_APP_SEARCH_CATEGORIES_INDEX,
  SEARCH_HASHTAGS_INDEX: process.env.REACT_APP_SEARCH_HASHTAGS_INDEX,
}

export default settings
