import { StyleSheet } from 'react-native'
import { Colors, Metrics, Fonts } from '../../Shared/Themes/'

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    marginTop: 0,
  },
  imageContainer: {
    position: 'relative',
    width: '100%',
    height: '100%',
    backgroundColor: Colors.backgroundDark,
  },
  videoContainer: {
    position: 'relative',
    width: Metrics.screenWidth,
    height: Metrics.screenHeight,
  },
  videoInnerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  imageOverlayContainer: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,.25)',
  },
  sliderOverlayContainer: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
  },
  sliderHeader: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: Metrics.baseMargin,
    paddingHorizontal: Metrics.baseMargin,
  },
  listContainer: {
    paddingBottom: Metrics.baseMargin,
  },
  contentContainer: {
    position: 'relative',
    marginLeft: Metrics.marginHorizontal / 2,
    alignSelf: 'center',
    width: Metrics.postCard.listing.cardWidth,
    height: '100%',
    borderRadius: 3,
    overflow: 'hidden',
  },
  newPostContainer: {
    position: 'relative',
    marginLeft: Metrics.marginHorizontal / 2,
    alignSelf: 'center',
    width: Metrics.postCard.listing.cardWidth,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: Colors.lightGrey,     
    borderRadius: 3,
    backgroundColor: Colors.whiteAlphaPt80,
    overflow: 'hidden',
  },
  innerContainer: {
    width: '100%',
    height: '100%',
  },
  newPostInnerContainer: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  formContainer: {
    padding: Metrics.doubleBaseMargin,
  },
  firstContentContainer: {
    marginLeft: Metrics.marginLeft,
  },
  lastContentContainer: {
    marginRight: Metrics.marginRight,
  },
  overlayContainer: {
    flex: 1,
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    paddingLeft: Metrics.paddingLeft,
    paddingRight: Metrics.paddingRight,
  },
  coverPhoto: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    width: '100%',
  },
  caption: {
    position: 'absolute',
    bottom: Metrics.postCard.listing.cardMarginBottom,
    fontFamily: Fonts.type.base,
    fontSize: Fonts.size.medium,
    fontWeight: 'bold',
    textAlign: 'left',
    color: Colors.white,
    paddingHorizontal: Metrics.baseMargin,
  },
  newPostCaption: {
    fontFamily: Fonts.type.base,
    fontSize: Fonts.size.small,
    fontWeight: 'bold',
    textAlign: 'center',
    color: Colors.blackoutTint,
  },
  message: {
    marginTop: Metrics.baseMargin,
    marginHorizontal: Metrics.baseMargin,
    textAlign: 'center',
    fontFamily: Fonts.type.base,
    fontSize: Fonts.size.regular,
    fontWeight: 'bold',
    color: Colors.steel,
  },
  icon: {
    color: Colors.steel,
  },
  titleInput: {
    color: Colors.white,
    fontSize: 20,
    fontFamily: Fonts.type.montserrat,
    fontWeight: '600',
    lineHeight: 33,
    marginTop: 15,
    paddingTop: 0,
  },
  navBarStyle: {
    height: Metrics.navBarHeight + 20,
    paddingTop: 0,
    color: Colors.snow,
    backgroundColor: Colors.transparent,
  },
  navBarTitleStyle: {
    display: 'none',
  },
  navBarLeftTextStyle: {
    color: Colors.white,
    justifyContent: 'flex-start',
  },
  navBarRightTextStyle: {
    color: Colors.snow,
    justifyContent: 'flex-end',
  },
  locationInputStyle: {
    borderWidth: 0,
    color: Colors.white,
  },
  publishBtnStyle: {
    position: 'absolute',
    right: Metrics.doubleBaseMargin / 2,
    bottom: Metrics.doubleBaseMargin,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 20,
    paddingRight: 20,
    borderWidth: 0,
    backgroundColor: Colors.snow,
  },
  publishBtnTextStyle: {
    fontWeight: '600',
    color: '#000',
  },
  disabledBtnTextStyle: {
    color: 'rgba(0,0,0,.3)',
  },
})
